var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,b){a.raw=b;return a};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.arrayFromIterator=function(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c};$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};function getOffscreenPoint(){do var a=createVector(Math.random()*(windowWidth+1E3)-500,Math.random()*(windowHeight+1E3)-500);while(onScreen(a,100));return a}function onScreen(a,b){return a.x>=-b&&a.x<=windowWidth+b&&a.y>=-b&&a.y<=windowHeight+b}
function drawCurvedText(a){a.ctx.textFont("Courier New",a.scale);for(var b=0,c=(a.ctx.textWidth(a.str)+2*(a.str.length-1))/a.radius,d=0;d<a.str.length;d++){var e=a.str.charAt(d),f=a.ctx.textWidth(e);b+=f/2+2;var g=b/a.radius-c/2+a.offset;a.ctx.push();a.ctx.fill(a.color);a.ctx.translate(a.x,a.y);a.ctx.rotate(g);a.ctx.translate(0,-a.radius);a.ctx.textStyle(a.style?a.style:NORMAL);a.ctx.text(e,0,0);a.ctx.pop();b+=f/2}}function trimMaxLength(a,b){return a.length>b?a.substring(0,b-3).trim()+"...":a}
function Bubble(a){this.topStr=trimMaxLength(a.topStr,18);this.bottomStr=trimMaxLength(a.bottomStr,18);this.constRadius=this.radius=a.radius;this.textColor=color(a.textColor);this.borderColor=color(a.borderColor);this.relativeScale=a.relativeScale;if(a.image){var b=a.image,c=min(b.width,b.height);this.image=b.get(0,0,c,c);this.image.resize(MAX_RADIUS+RADIUS_EXPAND,MAX_RADIUS+RADIUS_EXPAND);this.image.mask(circleMask)}this.mass=1E3*a.radius;this.invMass=1/this.mass;this.location=createVector(a.x,a.y);
this.velocity=createVector(0,0);this.animation=new BubbleAnimation(a.radius);this.dragged=!1;this.url=a.url}
Bubble.prototype.update=function(){var a=p5.Vector.sub(this.location,createVector(mouseX,mouseY)).magSq()<=this.radius*this.radius;a&&(mouseDragging?cursor("grabbing"):cursor(HAND));this.animation.expanding=(!bubbleGrabbed||this.dragged)&&a;this.animation.update(FRAME_LEN);this.radius=this.animation.radius;!bubbleGrabbed&&a&&mouseDragging?this.dragged=bubbleGrabbed=!0:bubbleGrabbed||(this.dragged=!1);this.dragged?this.location=createVector(mouseX,mouseY):(this.velocity.add(getGravVector(this.location)),
onScreen(this.location,0)&&this.velocity.mult(velocityFactor),this.location.add(p5.Vector.mult(this.velocity,FRAME_LEN)));a&&wasClickAction&&.5<this.animation.percentOfFullSize()&&window.open(this.url,"_blank")};
Bubble.prototype.drawBatch=function(a){var b=2*this.animation.apparentRadius-2*this.animation.stroke;a.noStroke();a.fill(this.borderColor);a.ellipse(this.location.x,this.location.y,2*this.animation.apparentRadius);this.image?a.image(this.image,this.location.x,this.location.y,b,b):(a.fill("#FEEAE0"),a.ellipse(this.location.x,this.location.y,2*this.animation.apparentRadius-2*this.animation.stroke))};
Bubble.prototype.drawWShadow=function(a,b){var c=2*this.animation.apparentRadius-2*this.animation.stroke;a.push();a.noStroke();a.fill(this.borderColor);a.drawingContext.shadowOffsetX=2;a.drawingContext.shadowOffsetY=2;a.drawingContext.shadowBlur=8;a.drawingContext.shadowColor="rgba(0,0,0,0.5)";a.ellipse(this.location.x,this.location.y,2*this.animation.apparentRadius);a.pop();a.push();a.noStroke();this.image?a.image(this.image,this.location.x,this.location.y,c,c):(a.fill("#FEEAE0"),a.ellipse(this.location.x,
this.location.y,2*this.animation.apparentRadius-2*this.animation.stroke));a.pop()};
Bubble.prototype.drawLabel=function(a){var b=this.textColor;b.setAlpha(255*this.animation.percentOfFullSize());a={str:this.topStr,radius:this.animation.apparentRadius-this.animation.stroke+this.animation.stroke*lerp(.2,.3,1-this.relativeScale),scale:lerp(.7,.8,this.relativeScale)*this.animation.stroke,x:this.location.x,y:this.location.y,offset:this.animation.expanding?this.animation.percentOfFullSize()-1:1-this.animation.percentOfFullSize(),color:b,ctx:a};drawCurvedText(a);a.str=this.bottomStr;a.radius=
-(this.animation.apparentRadius-this.animation.stroke*lerp(.2,.3,1-this.relativeScale));a.style=BOLD;drawCurvedText(a)};function BubbleAnimation(a){this.apparentRadius=this.radius=a;this.stroke=this.apparentRadius/100*10;this.constRadius=a;this.expanding=!1}
BubbleAnimation.prototype.update=function(a){this.radius=min(max(this.radius+(this.expanding?1:-1)*a*50,this.constRadius),this.constRadius+10);this.apparentRadius=this.radius+5*(this.radius-this.constRadius);this.stroke=lerp(this.apparentRadius/(MAX_RADIUS+RADIUS_EXPAND)*MAX_STROKE,HOVER_STROKE,this.percentOfFullSize())};BubbleAnimation.prototype.percentOfFullSize=function(){return(this.radius-this.constRadius)/RADIUS_EXPAND};
function getGravVector(a){if(windowWidth>windowHeight){var b=windowHeight/2,c=createVector(b,b),d=createVector(windowWidth-b,b);a=a.x>=c.x&&a.x<=d.x?createVector(0,b-a.y):p5.Vector.sub(a.x>d.x?d:c,a)}else b=windowWidth/2,c=createVector(b,b),d=createVector(windowHeight-b,b),a=a.y<=c.y&&a.y>=d.y?createVector(0,b-a.x):p5.Vector.sub(a.y>d.y?d:c,a);a.normalize();a.mult(1E3*FRAME_LEN);return a}
function engineInitialize(a){velocityFactor=1;velocityDecreaseRate=.99995;bubbleQueue=[];bubbles=[];wasClickAction=mouseDragging=bubbleGrabbed=!1;finalBubbleAmt=void 0;hasSlowedDown=!1;createBubbles(a)}
function update(){bubbleQueue.length==finalBubbleAmt&&$("#loading-message").is(":visible")&&$("#loading-message").fadeOut();addBubbles();slowdown();cursor(ARROW);for(var a=$jscomp.makeIterator(bubbles),b=a.next();!b.done;b=a.next())b.value.update();for(a=0;a<bubbles.length-1;a++)for(b=a+1;b<bubbles.length;b++)resolveCollisionVelocity(bubbles[a],bubbles[b]);for(a=0;a<bubbles.length-1;a++)for(b=a+1;b<bubbles.length;b++)correctPositions(bubbles[a],bubbles[b])}
function render(){clear();buffer.clear();for(var a,b=[],c=$jscomp.makeIterator(bubbles),d=c.next();!d.done;d=c.next())d=d.value,d.animation.expanding?a=d:d.animation.radius!=d.animation.constRadius?b.push(d):d.drawBatch(buffer);push();drawingContext.shadowOffsetX=2;drawingContext.shadowOffsetY=2;drawingContext.shadowBlur=8;drawingContext.shadowColor="rgba(0,0,0,0.5)";image(buffer,0,0);pop();push();textAlign(CENTER,BASELINE);imageMode(CENTER);b=$jscomp.makeIterator(b);for(d=b.next();!d.done;d=b.next())c=
d.value,c.drawWShadow(this),c.drawLabel(this);a&&(a.drawWShadow(this),a.drawLabel(this));pop()}function createBubbles(a){getVAAndCharacterData(a,createCharacterBubbles,createVABubble)}function addBubbles(){bubbleQueue.length!=bubbles.length&&0==frameCount%INTRO_BUBBLE_EVERY_N_FRAME&&bubbles.push(bubbleQueue[bubbles.length])}
function slowdown(){velocityFactor=max(velocityFactor*=velocityDecreaseRate,.5);hasSlowedDown||bubbleQueue.length!=finalBubbleAmt||bubbleQueue.length!=bubbles.length||.998==velocityDecreaseRate||(hasSlowedDown=!0,setTimeout(function(){velocityDecreaseRate=.998},2E3))}
function createCharacterBubbles(a){$("#loading-message").hide().text("Creating bubbles...").fadeIn();finalBubbleAmt=min(MAX_BUBBLES,a.length);for(var b=0;b<finalBubbleAmt;b++)(function(c){a[c].picURL.includes("questionmark")?bubbleQueue.push(createCharacterBubble(a,c)):loadImage(a[c].picURL,function(d){bubbleQueue.push(createCharacterBubble(a,c,d))})})(b);finalBubbleAmt+=1}
function createVABubble(a){loadImage(a.picURL,function(b){var c=getOffscreenPoint();bubbleQueue.push(new Bubble({topStr:a.japaneseName,bottomStr:a.name,radius:100,x:c.x,y:c.y,textColor:"white",borderColor:"black",url:a.profileURL,image:b,relativeScale:1}))})}
function createCharacterBubble(a,b,c){var d=getOffscreenPoint(),e=lerp(0,5/6,Math.pow((MAX_BUBBLES-b)/MAX_BUBBLES,2));a=a[b];return new Bubble({topStr:a.name,bottomStr:a.animeStr,radius:60*e+40,x:d.x,y:d.y,textColor:"black",borderColor:"white",url:a.profileURL,image:c,relativeScale:e})}
function resolveCollisionVelocity(a,b){var c=p5.Vector.sub(b.location,a.location),d=c.magSq(),e=a.radius+b.radius;d>e*e||(d=Math.sqrt(d),0!=d?(penetration=e-d,c.normalize()):(penetration=a.radius,c=createVector(1,0)),e=p5.Vector.sub(b.velocity,a.velocity).dot(c),0<e||(e*=-(1+RESTITUTION),e/=a.invMass+b.invMass,c=p5.Vector.mult(c,e),a.velocity.sub(p5.Vector.div(c,a.mass)),b.velocity.add(p5.Vector.div(c,b.mass))))}
function correctPositions(a,b){var c=p5.Vector.sub(b.location,a.location),d=c.magSq(),e=a.radius+b.radius;d>e*e||(d=Math.sqrt(d),0!=d?(penetration=e-d,c.normalize()):(penetration=a.radius,c=createVector(1,0)),c=p5.Vector.mult(c,.9*Math.max(penetration-.08,0)),a.location.sub(p5.Vector.mult(c,.5)),b.location.add(p5.Vector.mult(c,.5)))}
firebase.initializeApp({apiKey:"AIzaSyBeWnUFPxySkPCuw-cmWMpJXi3TmutBopg",authDomain:"anime-site-7964a.firebaseapp.com",databaseURL:"https://anime-site-7964a.firebaseio.com",projectId:"anime-site-7964a",storageBucket:"anime-site-7964a.appspot.com",messagingSenderId:"778668092530",appId:"1:778668092530:web:3b8034da272cd62ff266eb",measurementId:"G-FDHXQDVPNC"});firebase.analytics();
function loadTopAnimes(a){$("#loading-message").hide().text("Getting data...").fadeIn();firebase.database().ref("tops").once("value").then(function(b){a(b.val());updateTops(b.val())},function(b){console.log(b)})}
function updateTops(a){var b=0;a=$jscomp.makeIterator(a);for(var c=a.next();!c.done;c=a.next())c=c.value,c.updated>b&&(b=c.updated);7<(Date.now()-b)/1E3/60/60/24&&(console.log(atob("cG9n")),retrieveTops(10,[],Date.now(),function(d){firebase.database().ref("tops").set(d,function(e){e&&console.log(e)})}))}
function retrieveTops(a,b,c,d){var e="https://api.jikan.moe/v3/top/anime/"+a+"/bypopularity";1==a?$.getJSON(e,function(f){b.push.apply(b,$jscomp.arrayFromIterable(parseTopsFromJSON(f,c)));d(b)}):$.getJSON(e,function(f){b.push.apply(b,$jscomp.arrayFromIterable(parseTopsFromJSON(f,c)));setTimeout(function(){retrieveTops(a-1,b,c,d)},1E3)})}
function parseTopsFromJSON(a,b){for(var c=[],d=$jscomp.makeIterator(a.top),e=d.next();!e.done;e=d.next())e=e.value,c.push({mal_id:e.mal_id,rank:e.rank,updated:b});return c}function getVAAndCharacterData(a,b,c){loadTopAnimes(function(d){$("#loading-message").hide().text("Retrieving voice actor...").fadeIn();$.getJSON("https://api.jikan.moe/v3/person/"+a,function(e){var f=parseCharactersFromJSON(e,d);b(f);c(parseVAFromJSON(e))})})}
function parseCharactersFromJSON(a,b){for(var c=[],d={},e=$jscomp.makeIterator(a.voice_acting_roles),f=e.next();!f.done;d={$jscomp$loop$prop$charID$11:d.$jscomp$loop$prop$charID$11},f=e.next()){f=f.value;d.$jscomp$loop$prop$charID$11=f.character.mal_id;var g=c.find(function(h){return function(k){return k.characterID==h.$jscomp$loop$prop$charID$11}}(d));if(g){var l=getRank(b,f.anime.mal_id);l&&(!g.rank||g.rank&&l<g.rank)&&(g.rank=l,g.animeID=f.anime.mal_id,g.animeStr=f.anime.name)}else c.push({name:switchFirstAndLast(f.character.name),
picURL:f.character.image_url,profileURL:f.character.url,animeID:f.anime.mal_id,characterID:d.$jscomp$loop$prop$charID$11,animeStr:f.anime.name,rank:getRank(b,f.anime.mal_id)})}c.sort(function(h,k){return(h.rank?h.rank:Number.MAX_SAFE_INTEGER)-(k.rank?k.rank:Number.MAX_SAFE_INTEGER)});return c}function parseVAFromJSON(a){return{name:a.name,picURL:a.image_url,profileURL:a.url,japaneseName:a.family_name+" "+a.given_name}}
function getRank(a,b){var c=a.find(function(d){return d.mal_id===b});return c?c.rank:c}function switchFirstAndLast(a){var b=a.search(", ");-1!=b&&(a=a.substring(b+2)+" "+a.substring(0,b));return a}
var FPS=60,FRAME_LEN=1/FPS,INTRO_BUBBLE_EVERY_N_FRAME=4,RESTITUTION=.1,MAX_RADIUS=120,RADIUS_EXPAND=10,MAX_STROKE=10,HOVER_STROKE=30,MAX_BUBBLES=55,velocityFactor,velocityDecreaseRate=.99995,bubbleQueue=[],bubbles=[],bubbleGrabbed=!1,mouseDragging=!1,wasClickAction=!1,circleMask,buffer,finalBubbleAmt,hasSlowedDown=!1;if("function"!==typeof Object.freeze)throw Error("Missing Object.freeze");Object.freeze(Bubble.prototype);Object.freeze(BubbleAnimation.prototype);engineInitialize(6686);
function setup(){circleMask=createGraphics(200,200);circleMask.circle(100,100,200);createCanvas(windowWidth,windowHeight).parent("bubble-area");frameRate(FPS);buffer=createGraphics(windowWidth,windowHeight);buffer.textAlign(CENTER,BASELINE);buffer.imageMode(CENTER)}function draw(){finalBubbleAmt&&bubbleQueue.length!=finalBubbleAmt||(update(),render(),wasClickAction=!1)}
function windowResized(){resizeCanvas(windowWidth,windowHeight);buffer=createGraphics(windowWidth,windowHeight);buffer.textAlign(CENTER,BASELINE);buffer.imageMode(CENTER);gravity=windowHeight}function mouseReleased(){mouseDragging||(wasClickAction=!0);mouseDragging=bubbleGrabbed=!1}function mouseDragged(){mouseDragging=!0};